require 'csv'

class City < Sequel::Model

  def self.import_data
    data = CSV.read('/home/ezra/Downloads/data/city_info.csv', headers: true)
    rows = data.to_a.map { |row| row.drop(1).take(4) }
    self.import [:name, :station_code, :lat, :long], rows.drop(1).uniq.sort
  end

end

# Table: cities
# Columns:
#  id           | integer          | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name         | text             |
#  station_code | text             |
#  lat          | double precision |
#  long         | double precision |
# Indexes:
#  cities_pkey | PRIMARY KEY btree (id)
# Referenced By:
#  readings | readings_city_id_fkey | (city_id) REFERENCES cities(id)
#  stations | stations_city_id_fkey | (city_id) REFERENCES cities(id)
