require 'csv'

class Station < Sequel::Model
  
  def self.import_data
    data = CSV.read('/home/ezra/Downloads/data/city_info.csv', headers: true)
    rows = data.to_a.map { |row| row.drop(1) }.drop(1)

    rows.each do |row|
      city_id = City.find(name: row.first).id
      station_data = row.drop(4).prepend(city_id)
      self.insert [:city_id, :station_name, :start_date, :end_date], station_data
    end
  end

end

# Table: stations
# Columns:
#  id           | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  city_id      | integer | NOT NULL
#  station_name | text    |
#  start_date   | date    |
#  end_date     | date    |
# Indexes:
#  stations_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  stations_city_id_fkey | (city_id) REFERENCES cities(id)
